## Function 1: Load and Explore GIS Data 📊

In this notebook, you'll learn how to build the `load_and_explore_gis_data()` function step by step. This is like opening a spreadsheet file and getting familiar with what's inside.

### 🎯 What This Function Does
- Loads a CSV file into a pandas DataFrame
- Shows you key information about the dataset
- Displays the first few rows so you can see what the data looks like
- Provides summary statistics
- Handles errors gracefully

### 🔧 Function Signature
```python
def load_and_explore_gis_data(file_path):
    """
    Args:
        file_path (str): Path to CSV file (e.g., 'data/weather_stations.csv')
    
    Returns:
        pandas.DataFrame: The loaded dataset
    """
```

### 📍 Where This Function Goes:
**Target File**: `src/pandas_basics.py`  
**Function Name**: `load_and_explore_gis_data()`  
**Replace**: The TODO comments with your working code

---

### ⚙️ Step 0: Select the Correct Python Kernel

Before running any cells, make sure the notebook is using the correct Python environment.

**Check the kernel in the top-right corner of the notebook.**

The correct Python environment is **python-gis-development (.venv)**  
It may appear with a Python version, for example:  
**python-gis-development (3.11.15) (Python 3.11.15) .venv/bin/python**



If the kernel is **python-gis-development (.venv)**, you can start running cells below.

Steps to select the correct kernel:
1. Click on the kernel (top right corner of the notebook) if it is not **python-gis-development (.venv)** or if it says "Select Kernel"
2. Select **python-gis-development (.venv)**
3. If you do not see the kernel in the list, click on "Select Another Kernel..."  
    a. Click on Python Environments...   
    b. Select **python-gis-development (.venv)**

Once the correct kernel is selected, you can start running cells below.

### 🚀 Step 1: Import Required Libraries

First, let's import the libraries we need:

In [1]:
import pandas as pd
import os

print(f"✅ Pandas version: {pd.__version__}")
print("📚 Ready to work with data!")

✅ Pandas version: 3.0.1
📚 Ready to work with data!

### 📁 Step 2: Understanding File Paths

Before we load data, let's understand where our files are located:

In [2]:
# Let's see what files we have in the data directory
data_dir = '../../data'  # Go up two levels from notebooks/pandas, then into data

if os.path.exists(data_dir):
    print("📂 Files in data directory:")
    for file in os.listdir(data_dir):
        print(f"   {file}")
else:
    print(f"❌ Directory not found: {data_dir}")
    print("Current working directory:", os.getcwd())

📂 Files in data directory:
   temperature_readings.csv
   weather_stations.csv
   neighborhood_samples.geojson

### 📊 Step 3: Loading Your First CSV File

Now let's load the weather stations data and see what happens:

In [3]:
# Define the file path
file_path = '../../data/weather_stations.csv'

# Load the CSV file into a DataFrame
try:
    df = pd.read_csv(file_path)
    print("✅ File loaded successfully!")
    print(f"📁 Loaded: {file_path}")
except FileNotFoundError:
    print(f"❌ File not found: {file_path}")
    print("Check the file path and confirm the dataset exists in the data folder.")
except Exception as e:
    print(f"❌ Error loading file: {e}")

✅ File loaded successfully!
📁 Loaded: ../../data/weather_stations.csv

### 🔍 Step 4: Exploring the Dataset Shape and Structure

When you first load data, you want to understand:
- How many rows and columns does it have?
- What are the column names?
- What data types are in each column?

In [4]:
# Show the shape (rows, columns)
print(f"📏 Shape: {df.shape} - {df.shape[0]} rows and {df.shape[1]} columns")
print()

# Show column names
print("📋 Columns:")
for i, col in enumerate(df.columns):
    print(f"   {i+1}. {col}")
print()

# Show data types and memory usage
print("🔧 Data Types and Info:")
df.info()

📏 Shape: (15, 6) - 15 rows and 6 columns

📋 Columns:
   1. station_id
   2. station_name
   3. latitude
   4. longitude
   5. elevation_m
   6. station_type

🔧 Data Types and Info:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   station_id    15 non-null     str
 1   station_name  15 non-null     str
 2   latitude      15 non-null     float64
 3   longitude     15 non-null     float64
 4   elevation_m   15 non-null     int64
 5   station_type  15 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 852.0 bytes

### 👀 Step 5: Looking at the Actual Data

Numbers and column names are helpful, but you need to see the actual data to understand what you're working with:

In [5]:
# Show the first 5 rows
print("🔍 First 5 rows:")
display(df.head())

print("\n" + "="*50)

# You can also show the last few rows
print("🔍 Last 3 rows:")
display(df.tail(3))

🔍 First 5 rows:

,station_id,station_name,latitude,longitude,elevation_m,station_type
0,STN_001,Central Park Weather Station,40.7829,-73.9654,35,meteorological
1,STN_002,Times Square Monitor,40.7580,-73.9855,10,air_quality
2,STN_003,Brooklyn Bridge Station,40.7061,-73.9969,25,meteorological
3,STN_004,Queens Plaza Monitor,40.7505,-73.9370,15,air_quality
4,STN_005,Staten Island Station,40.5795,-74.1502,45,meteorological

==================================================
🔍 Last 3 rows:

,station_id,station_name,latitude,longitude,elevation_m,station_type
12,STN_013,Coney Island Station,40.5755,-73.9707,3,meteorological
13,STN_014,LaGuardia Monitor,40.7769,-73.8740,21,air_quality
14,STN_015,Battery Park Station,40.7033,-74.0170,4,air_quality

### 📈 Step 6: Summary Statistics

Summary statistics help you understand the range and distribution of numerical data:

In [6]:
# Show summary statistics for numerical columns
print("📊 Summary Statistics:")
display(df.describe())

# For text columns, you can see unique values
print("\n📝 Text Column Analysis:")
for col in df.select_dtypes(include=['object']).columns:
    unique_count = df[col].nunique()
    print(f"   {col}: {unique_count} unique values")
    if unique_count <= 10:  # Show values if not too many
        print(f"      Values: {list(df[col].unique())[:10]}")

📊 Summary Statistics:

        latitude  longitude  elevation_m
count  15.000000  15.000000    15.000000
mean   40.715900 -73.969607    27.600000
std     0.078646   0.084509    25.858958
min    40.575500 -74.150200     3.000000
25%    40.675500 -74.008050     9.000000
50%    40.707400 -73.970700    18.000000
75%    40.767450 -73.949800    40.000000
max    40.850600 -73.778100    85.000000

📝 Text Column Analysis:
   station_id: 15 unique values
   station_name: 15 unique values
   station_type: 2 unique values
      Values: ['meteorological', 'air_quality']

/tmp/ipykernel_3315/1244436675.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

⚠️ Note the warning message. This warning is related to a change in **pandas**.

Historically, pandas stored text data using the **`object`** data type. Newer versions of pandas now support a dedicated **`string`** data type. In future versions, text columns may use `string` instead of `object`.

Because of this transition, pandas warns that selecting only `object` columns may eventually miss some text columns.

To ensure compatibility with both current and future versions of pandas, we can explicitly include both types:

```python
df.select_dtypes(include=['object', 'string'])
```

This is a good real-world example of how software libraries evolve over time and why it is important to pay attention to warnings in your code.

### 🔧 Step 7: Checking for Data Quality Issues

Real-world data often has problems. Let's check for common issues:

In [7]:
# Check for missing values
print("🔍 Missing Values Check:")
missing_data = df.isnull().sum()
if missing_data.sum() > 0:
    print(missing_data[missing_data > 0])
else:
    print("✅ No missing values found!")

print("\n🔍 Duplicate Rows Check:")
duplicate_count = df.duplicated().sum()
if duplicate_count > 0:
    print(f"⚠️  Found {duplicate_count} duplicate rows")
else:
    print("✅ No duplicate rows found!")

🔍 Missing Values Check:
✅ No missing values found!

🔍 Duplicate Rows Check:
✅ No duplicate rows found!

### 🧪 Step 8: Test with the Temperature Readings Data

Let's try our exploration technique with the other dataset:

In [8]:
# Load the temperature readings dataset
temp_file = '../../data/temperature_readings.csv'
temp_df = pd.read_csv(temp_file)

print(f"🌡️  Temperature Readings Dataset")
print(f"Shape: {temp_df.shape}")
print(f"Columns: {list(temp_df.columns)}")
print("\nFirst 3 rows:")
display(temp_df.head(3))

print("\nSummary statistics:")
display(temp_df.describe())

🌡️  Temperature Readings Dataset
Shape: (95, 5)
Columns: ['station_id', 'date', 'temperature_c', 'humidity_percent', 'data_quality']

First 3 rows:

  station_id        date  temperature_c  humidity_percent data_quality
0    STN_001  2023-01-15           22.5              65.2         good
1    STN_001  2023-01-16           23.1              68.4         good
2    STN_001  2023-01-17           21.8              62.7         good

Summary statistics:

       temperature_c  humidity_percent
count      95.000000         95.000000
mean       22.644211         66.013684
std         3.484486         11.318819
min        14.900000         38.400000
25%        20.250000         58.600000
50%        22.700000         67.800000
75%        25.000000         74.150000
max        35.200000         88.300000

### 🏗️ Step 9: Building the Complete Function

Now let's put everything together into a reusable function. This is what you will implement in `src/pandas_basics.py`:

Find this:
```python
def load_and_explore_gis_data(file_path):
    # TODO: Print a header to show what function is running
    # TODO: Use something like print("=" * 50)
    # ... (lots more TODO comments)
```
Replace ALL the TODO comments with your working code from below

In [9]:
def load_and_explore_gis_data(file_path):
    """
    Load a CSV file and display comprehensive information about the dataset.
    
    This function demonstrates the first step in any data analysis project:
    understanding your data through exploration.
    
    Args:
        file_path (str): Path to the CSV file to load
        
    Returns:
        pandas.DataFrame: The loaded dataset, or None if loading failed
    """
    
    print("=" * 50)
    print("LOADING AND EXPLORING GIS DATA")
    print("=" * 50)
    
    # Step 1: Check if file exists
    if not os.path.exists(file_path):
        print(f"❌ ERROR: File not found: {file_path}")
        print("Please check:")
        print("- Is the file path correct?")
        print("- Are you in the right directory?")
        print("- Does the file exist?")
        return None
    
    print(f"📁 Loading data from: {file_path}")
    
    # Step 2: Load the CSV file
    try:
        df = pd.read_csv(file_path)
        print("✅ File loaded successfully!")
    except Exception as e:
        print(f"❌ ERROR loading file: {e}")
        return None
    
    # Step 3: Show basic dataset information
    print(f"\n📊 DATASET OVERVIEW")
    print(f"Shape: {df.shape} - {df.shape[0]} rows and {df.shape[1]} columns")
    print(f"Columns: {list(df.columns)}")
    
    # Step 4: Show data types
    print(f"\n🔧 DATA TYPES:")
    for col in df.columns:
        print(f"   {col}: {df[col].dtype}")
    
    # Step 5: Show first few rows
    print(f"\n👀 FIRST 5 ROWS:")
    print(df.head())
    
    # Step 6: Show summary statistics
    print(f"\n📈 SUMMARY STATISTICS:")
    print(df.describe())
    
    # Step 7: Check for data quality issues
    print(f"\n🔍 DATA QUALITY CHECK:")
    missing = df.isnull().sum()
    if missing.sum() > 0:
        print("Missing values found:")
        print(missing[missing > 0])
    else:
        print("✅ No missing values")
        
    duplicates = df.duplicated().sum()
    if duplicates > 0:
        print(f"⚠️  Found {duplicates} duplicate rows")
    else:
        print("✅ No duplicate rows")
    
    print(f"\n🎉 Data exploration complete! Dataset is ready for analysis.")
    
    return df

### ✨ Step 10: Test Your Function

Let's test our complete function with both datasets:

In [10]:
# Test 1: with weather stations
print("🧪 TESTING WITH WEATHER STATIONS DATA\n")
stations_df = load_and_explore_gis_data('../../data/weather_stations.csv')

🧪 TESTING WITH WEATHER STATIONS DATA

==================================================
LOADING AND EXPLORING GIS DATA
==================================================
📁 Loading data from: ../../data/weather_stations.csv
✅ File loaded successfully!

📊 DATASET OVERVIEW
Shape: (15, 6) - 15 rows and 6 columns
Columns: ['station_id', 'station_name', 'latitude', 'longitude', 'elevation_m', 'station_type']

🔧 DATA TYPES:
   station_id: str
   station_name: str
   latitude: float64
   longitude: float64
   elevation_m: int64
   station_type: str

👀 FIRST 5 ROWS:
  station_id                  station_name  latitude  longitude  elevation_m  \
0    STN_001  Central Park Weather Station   40.7829   -73.9654           35
1    STN_002          Times Square Monitor   40.7580   -73.9855           10
2    STN_003       Brooklyn Bridge Station   40.7061   -73.9969           25
3    STN_004          Queens Plaza Monitor   40.7505   -73.9370           15
4    STN_005         Staten Island Station   40.5795   -74.1502           45

     station_type
0  meteorological
1     air_quality
2  meteorological
3     air_quality
4  meteorological

📈 SUMMARY STATISTICS:
        latitude  longitude  elevation_m
count  15.000000  15.000000    15.000000
mean   40.715900 -73.969607    27.600000
std     0.078646   0.084509    25.858958
min    40.575500 -74.150200     3.000000
25%    40.675500 -74.008050     9.000000
50%    40.707400 -73.970700    18.000000
75%    40.767450 -73.949800    40.000000
max    40.850600 -73.778100    85.000000

🔍 DATA QUALITY CHECK:
✅ No missing values
✅ No duplicate rows

🎉 Data exploration complete! Dataset is ready for analysis.

In [11]:
# Test 2: with temperature readings
print("\n" + "="*80 + "\n")
print("🧪 TESTING WITH TEMPERATURE READINGS DATA\n")
readings_df = load_and_explore_gis_data('../../data/temperature_readings.csv')

================================================================================

🧪 TESTING WITH TEMPERATURE READINGS DATA

==================================================
LOADING AND EXPLORING GIS DATA
==================================================
📁 Loading data from: ../../data/temperature_readings.csv
✅ File loaded successfully!

📊 DATASET OVERVIEW
Shape: (95, 5) - 95 rows and 5 columns
Columns: ['station_id', 'date', 'temperature_c', 'humidity_percent', 'data_quality']

🔧 DATA TYPES:
   station_id: str
   date: str
   temperature_c: float64
   humidity_percent: float64
   data_quality: str

👀 FIRST 5 ROWS:
  station_id        date  temperature_c  humidity_percent data_quality
0    STN_001  2023-01-15           22.5              65.2         good
1    STN_001  2023-01-16           23.1              68.4         good
2    STN_001  2023-01-17           21.8              62.7         good
3    STN_001  2023-01-18           24.2              70.1         good
4    STN_001  2023-01-19           20.9              59.3         fair

📈 SUMMARY STATISTICS:
       temperature_c  humidity_percent
count      95.000000         95.000000
mean       22.644211         66.013684
std         3.484486         11.318819
min        14.900000         38.400000
25%        20.250000         58.600000
50%        22.700000         67.800000
75%        25.000000         74.150000
max        35.200000         88.300000

🔍 DATA QUALITY CHECK:
✅ No missing values
✅ No duplicate rows

🎉 Data exploration complete! Dataset is ready for analysis.

In [12]:
# Test 3: error handling with non-existent file
print("\n" + "="*80 + "\n")
print("🧪 TESTING ERROR HANDLING\n")
result = load_and_explore_gis_data('../../data/nonexistent_file.csv')
print(f"Result: {result}")

================================================================================

🧪 TESTING ERROR HANDLING

==================================================
LOADING AND EXPLORING GIS DATA
==================================================
❌ ERROR: File not found: ../../data/nonexistent_file.csv
Please check:
- Is the file path correct?
- Are you in the right directory?
- Does the file exist?
Result: None

### 🧪 Step 11: Verify with Pytest

Test your entire function to verify your implementation in `src/pandas_basics.py` by running the following line in the terminal

```bash
uv run pytest tests/test_pandas_basics.py::TestLoadAndExploreGISData -v

```

**⚠️ IMPORTANT: Make sure this passes before you move on!**

---


### 🔑 Key Learning Points

- **`pd.read_csv()`** loads CSV files into DataFrames
- **`.shape`** tells you rows and columns: `(rows, columns)`
- **`.head()`** shows the first few rows
- **`.info()`** shows data types and memory usage
- **`.describe()`** shows summary statistics for numerical columns
- Always check for missing values and data quality issues
- Error handling makes your code robust and user-friendly