## Function 3: Calculate Station Statistics 📈

In this notebook, you'll learn how to build the `calculate_station_statistics()` function step by step. This is like taking many individual readings from each weather station and turning them into a clean station-by-station summary.

### 🎯 What This Function Does
- Groups environmental readings by station
- Calculates average temperature for each station
- Calculates average humidity for each station
- Counts how many readings each station has
- Returns a clean summary DataFrame for reporting and analysis

### 🔧 Function Signature
```python
def calculate_station_statistics(df):
    """
    Args:
        df (pandas.DataFrame): Environmental monitoring data
    
    Returns:
        pandas.DataFrame: Summary statistics by station
    """
```

### 📍 Where This Function Goes:
**Target File**: `src/pandas_basics.py`  
**Function Name**: `calculate_station_statistics()`  
**Replace**: The TODO comments with your working code

---

### ⚙️ Step 0: Select the Correct Python Kernel

Before running any cells, make sure the notebook is using the correct Python environment.

**Check the kernel in the top-right corner of the notebook.**

The correct Python environment is **python-gis-development (.venv)**  
It may appear with a Python version, for example:  
**python-gis-development (3.11.15) (Python 3.11.15) .venv/bin/python**



If the kernel is **python-gis-development (.venv)**, you can start running cells below.

Steps to select the correct kernel:
1. Click on the kernel (top right corner of the notebook) if it is not **python-gis-development (.venv)** or if it says "Select Kernel"
2. Select **python-gis-development (.venv)**
3. If you do not see the kernel in the list, click on "Select Another Kernel..."  
    a. Click on Python Environments...   
    b. Select **python-gis-development (.venv)**

Once the correct kernel is selected, you can start running cells below.

### 🚀 Step 1: Import Required Libraries and Load Data

First, let's import the libraries we need and load the temperature readings data:

In [1]:
import pandas as pd

print(f"✅ Pandas version: {pd.__version__}")
print("📊 Ready to calculate station statistics!")

# Load the temperature readings data
file_path = '../../data/temperature_readings.csv'
df = pd.read_csv(file_path)

print(f"📊 Loaded {len(df)} temperature readings")
print(f"📋 Columns: {list(df.columns)}")
print("\n🔍 First 5 rows:")
display(df.head())

✅ Pandas version: 3.0.1
📊 Ready to calculate station statistics!
📊 Loaded 95 temperature readings
📋 Columns: ['station_id', 'date', 'temperature_c', 'humidity_percent', 'data_quality']

🔍 First 5 rows:

  station_id        date  temperature_c  humidity_percent data_quality
0    STN_001  2023-01-15           22.5              65.2         good
1    STN_001  2023-01-16           23.1              68.4         good
2    STN_001  2023-01-17           21.8              62.7         good
3    STN_001  2023-01-18           24.2              70.1         good
4    STN_001  2023-01-19           20.9              59.3         fair

### 🔍 Step 2: Understand the Data Before Grouping

Before using `.groupby()`, let's see what stations are in the dataset and how many readings each one has:

In [2]:
unique_stations = df['station_id'].unique()

print("🏷️ Unique stations:")
print(list(unique_stations))
print(f"\n📍 Number of stations: {len(unique_stations)}")

print("\n📊 Readings per station:")
print(df['station_id'].value_counts().sort_index())

🏷️ Unique stations:
['STN_001', 'STN_002', 'STN_003', 'STN_004', 'STN_005', 'STN_006', 'STN_007', 'STN_008', 'STN_009', 'STN_010', 'STN_011', 'STN_012', 'STN_013', 'STN_014', 'STN_015']

📍 Number of stations: 15

📊 Readings per station:
station_id
STN_001    7
STN_002    7
STN_003    7
STN_004    7
STN_005    7
STN_006    6
STN_007    6
STN_008    6
STN_009    6
STN_010    6
STN_011    6
STN_012    6
STN_013    6
STN_014    6
STN_015    6
Name: count, dtype: int64

### 🧠 Step 3: Learn How `.groupby()` Works

The `.groupby()` method splits the data into groups. Here, each group represents one station:

In [3]:
# Create a groupby object
grouped = df.groupby('station_id')

print("🔧 GroupBy object created")
print(f"Type: {type(grouped)}")
print(f"Number of groups: {grouped.ngroups}")

print("\n📂 Group information:")
for name, group in grouped:
    print(f"   {name}: {len(group)} rows")
    if name == unique_stations[0]:
        print(f"\n🔍 Sample from {name}:")
        display(group[['temperature_c', 'humidity_percent']].head(3))
        break

🔧 GroupBy object created
Type: <class 'pandas.api.typing.DataFrameGroupBy'>
Number of groups: 15

📂 Group information:
   STN_001: 7 rows

🔍 Sample from STN_001:

   temperature_c  humidity_percent
0           22.5              65.2
1           23.1              68.4
2           21.8              62.7

### 📈 Step 4: Calculate Basic Statistics for Each Station

Now let's calculate the summary values we want for each station:

In [4]:
# Average temperature by station
avg_temperature = grouped['temperature_c'].mean().round(1)
print("🌡️ Average temperature by station:")
print(avg_temperature)

print("\n" + "=" * 50 + "\n")

# Average humidity by station
avg_humidity = grouped['humidity_percent'].mean().round(1)
print("💧 Average humidity by station:")
print(avg_humidity)

print("\n" + "=" * 50 + "\n")

# Reading count by station
reading_count = grouped.size()
print("🔢 Reading count by station:")
print(reading_count)

🌡️ Average temperature by station:
station_id
STN_001    22.5
STN_002    24.2
STN_003    19.9
STN_004    26.9
STN_005    18.6
STN_006    25.2
STN_007    21.0
STN_008    22.4
STN_009    24.4
STN_010    20.4
STN_011    26.1
STN_012    17.7
STN_013    23.4
STN_014    22.2
STN_015    24.9
Name: temperature_c, dtype: float64

==================================================

💧 Average humidity by station:
station_id
STN_001    64.8
STN_002    68.7
STN_003    58.4
STN_004    80.6
STN_005    49.1
STN_006    70.9
STN_007    63.4
STN_008    68.2
STN_009    72.9
STN_010    59.9
STN_011    77.9
STN_012    46.8
STN_013    69.6
STN_014    66.0
STN_015    74.2
Name: humidity_percent, dtype: float64

==================================================

🔢 Reading count by station:
station_id
STN_001    7
STN_002    7
STN_003    7
STN_004    7
STN_005    7
STN_006    6
STN_007    6
STN_008    6
STN_009    6
STN_010    6
STN_011    6
STN_012    6
STN_013    6
STN_014    6
STN_015    6
dtype: int64

### 🏗️ Step 5: Build a Summary DataFrame

Next, let's combine those separate results into one clean summary table:

In [5]:
summary_df = pd.DataFrame({
    'station_id': avg_temperature.index,
    'avg_temperature': avg_temperature.values,
    'avg_humidity': avg_humidity.values,
    'reading_count': reading_count.values
})

print("📋 Station summary DataFrame:")
display(summary_df)

📋 Station summary DataFrame:

   station_id  avg_temperature  avg_humidity  reading_count
0     STN_001             22.5          64.8              7
1     STN_002             24.2          68.7              7
2     STN_003             19.9          58.4              7
3     STN_004             26.9          80.6              7
4     STN_005             18.6          49.1              7
5     STN_006             25.2          70.9              6
6     STN_007             21.0          63.4              6
7     STN_008             22.4          68.2              6
8     STN_009             24.4          72.9              6
9     STN_010             20.4          59.9              6
10    STN_011             26.1          77.9              6
11    STN_012             17.7          46.8              6
12    STN_013             23.4          69.6              6
13    STN_014             22.2          66.0              6
14    STN_015             24.9          74.2              6

### 🔍 Step 6: Explore the Summary Results

Once the summary table is built, we can inspect it to find useful patterns:

In [6]:
print("📊 Summary overview:")
print(f"Temperature range: {summary_df['avg_temperature'].min():.1f}°C to {summary_df['avg_temperature'].max():.1f}°C")
print(f"Humidity range: {summary_df['avg_humidity'].min():.1f}% to {summary_df['avg_humidity'].max():.1f}%")
print(f"Total readings represented: {summary_df['reading_count'].sum():,}")

hottest_station = summary_df.loc[summary_df['avg_temperature'].idxmax()]
coolest_station = summary_df.loc[summary_df['avg_temperature'].idxmin()]

print(f"\n🔥 Hottest station: {hottest_station['station_id']} ({hottest_station['avg_temperature']:.1f}°C)")
print(f"❄️ Coolest station: {coolest_station['station_id']} ({coolest_station['avg_temperature']:.1f}°C)")

📊 Summary overview:
Temperature range: 17.7°C to 26.9°C
Humidity range: 46.8% to 80.6%
Total readings represented: 95

🔥 Hottest station: STN_004 (26.9°C)
❄️ Coolest station: STN_012 (17.7°C)

### 🏗️ Step 7: Building the Complete Function

Now let's put everything together into a reusable function. This is what you will implement in `src/pandas_basics.py`:

Find this:
```python
def calculate_station_statistics(df):
    # TODO: Print header with function name
    # TODO: Validate input DataFrame (check if None or empty)
    # ... (lots more TODO comments)
```
Replace ALL the TODO comments with your working code from below

In [7]:
def calculate_station_statistics(df):
    """
    Calculate station statistics
    
    This function groups temperature readings by weather station and calculates
    summary statistics (average temperature, number of readings, etc.) for each
    station.
    
    Args:
        df (pandas.DataFrame): Environmental readings data with 'station_id', 'temperature_c' and 'humidity_percent' columns
    
    Returns:
        pandas.DataFrame: Statistics for each station with columns:
            - station_id: The weather station identifier
            - avg_temperature: Average temperature for this station
            - avg_humidity: Average humidity for this station
            - reading_count: Number of readings from this station
    """
    
    # Print header
    print("=" * 50)
    print("CALCULATING STATION STATISTICS")
    print("=" * 50)
    
    # Input validation
    if df is None or len(df) == 0:
        print("❌ ERROR: DataFrame is empty or None")
        return pd.DataFrame()
    
    # Check for required columns
    required_columns = ['station_id', 'temperature_c', 'humidity_percent']
    missing_columns = [col for col in required_columns if col not in df.columns]
    
    if missing_columns:
        print(f"❌ ERROR: Missing required columns: {missing_columns}")
        print(f"Available columns: {list(df.columns)}")
        return pd.DataFrame()
    
    # Print input data summary
    print(f"Processing {len(df):,} temperature readings...")
    
    # Get unique stations
    unique_stations = df['station_id'].unique()
    print(f"Found {len(unique_stations)} weather stations: {list(unique_stations)}")
    
    # Group data by station
    grouped = df.groupby('station_id')
    
    # Calculate statistics
    avg_temperature = grouped['temperature_c'].mean().round(1)
    avg_humidity = grouped['humidity_percent'].mean().round(1)
    reading_count = grouped.size()
    
    # Create summary DataFrame
    summary = pd.DataFrame({
        'station_id': avg_temperature.index,
        'avg_temperature': avg_temperature.values,
        'avg_humidity': avg_humidity.values,
        'reading_count': reading_count.values
    })
    
    # Print summary of results
    print(f"\nTemperature range across all stations: {summary['avg_temperature'].min():.1f}°C to {summary['avg_temperature'].max():.1f}°C")
    print(f"Humidity range across all stations: {summary['avg_humidity'].min():.1f}% to {summary['avg_humidity'].max():.1f}%")
    print(f"Total readings processed: {summary['reading_count'].sum():,}")
    print(f"Average readings per station: {summary['reading_count'].mean():.0f}")
    
    # Find temperature extremes
    hottest_station = summary.loc[summary['avg_temperature'].idxmax()]
    coolest_station = summary.loc[summary['avg_temperature'].idxmin()]
    
    print(f"\nHottest station: {hottest_station['station_id']} (avg: {hottest_station['avg_temperature']:.1f}°C)")
    print(f"Coolest station: {coolest_station['station_id']} (avg: {coolest_station['avg_temperature']:.1f}°C)")
    
    print("\nStation statistics calculated successfully!")
    
    return summary

### ✨ Step 8: Test Your Complete Function

Let's test our complete function with different scenarios:

In [8]:
# Test #1: Test with CSV
print("🧪 TESTING WITH TEMPERATURE READINGS CSV\n")
csv_station_stats = calculate_station_statistics(df)

print("\n📋 Final CSV results:")
display(csv_station_stats)

🧪 TESTING WITH TEMPERATURE READINGS CSV

==================================================
CALCULATING STATION STATISTICS
==================================================
Processing 95 temperature readings...
Found 15 weather stations: ['STN_001', 'STN_002', 'STN_003', 'STN_004', 'STN_005', 'STN_006', 'STN_007', 'STN_008', 'STN_009', 'STN_010', 'STN_011', 'STN_012', 'STN_013', 'STN_014', 'STN_015']

Temperature range across all stations: 17.7°C to 26.9°C
Humidity range across all stations: 46.8% to 80.6%
Total readings processed: 95
Average readings per station: 6

Hottest station: STN_004 (avg: 26.9°C)
Coolest station: STN_012 (avg: 17.7°C)

Station statistics calculated successfully!

📋 Final CSV results:

   station_id  avg_temperature  avg_humidity  reading_count
0     STN_001             22.5          64.8              7
1     STN_002             24.2          68.7              7
2     STN_003             19.9          58.4              7
3     STN_004             26.9          80.6              7
4     STN_005             18.6          49.1              7
5     STN_006             25.2          70.9              6
6     STN_007             21.0          63.4              6
7     STN_008             22.4          68.2              6
8     STN_009             24.4          72.9              6
9     STN_010             20.4          59.9              6
10    STN_011             26.1          77.9              6
11    STN_012             17.7          46.8              6
12    STN_013             23.4          69.6              6
13    STN_014             22.2          66.0              6
14    STN_015             24.9          74.2              6

In [9]:
# Test #2: Error handling with an empty DataFrame
print("\n" + "=" * 80 + "\n")
print("🧪 TESTING ERROR HANDLING - EMPTY DATAFRAME\n")
empty_df = pd.DataFrame()
result_empty = calculate_station_statistics(empty_df)
print(result_empty)

================================================================================

🧪 TESTING ERROR HANDLING - EMPTY DATAFRAME

==================================================
CALCULATING STATION STATISTICS
==================================================
❌ ERROR: DataFrame is empty or None
Empty DataFrame
Columns: []
Index: []

In [10]:
# Test #3: Error handling with missing columns
print("\n" + "=" * 80 + "\n")
print("🧪 TESTING ERROR HANDLING - MISSING COLUMNS\n")
bad_df = df[['station_id', 'temperature_c']].copy()
result_bad = calculate_station_statistics(bad_df)
print(result_bad)

================================================================================

🧪 TESTING ERROR HANDLING - MISSING COLUMNS

==================================================
CALCULATING STATION STATISTICS
==================================================
❌ ERROR: Missing required columns: ['humidity_percent']
Available columns: ['station_id', 'temperature_c']
Empty DataFrame
Columns: []
Index: []

### 🧪 Step 9: Verify with Pytest

Test your entire function to verify your implementation in `src/pandas_basics.py` by running the following line in the terminal

```bash
uv run pytest tests/test_pandas_basics.py::TestCalculateStationStatistics -v

```

**⚠️ IMPORTANT: Make sure this passes before you move on!**

---

### 🔑 Key Learning Points

- **`df.groupby('station_id')`** splits data into groups by station
- **`.mean()`** calculates averages for each group
- **`.size()`** counts how many rows each group contains
- You can combine multiple grouped results into a new summary DataFrame
- **`.round(1)`** helps format values to one decimal place
- Always check that your required columns exist before processing
- Grouping and aggregation help turn raw data into useful summaries